version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: intimatecare-web
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production 