version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: intimatecare-web
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./ssl:/etc/nginx/ssl