[build]
  command = "npm run build"
  publish = "dist"

# Handle SPA routing for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Domain redirects - ensure both www and non-www versions work
[[redirects]]
  from = "https://intimatecare.in/*"
  to = "https://www.intimatecare.in/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://intimatecare.in/*"
  to = "https://www.intimatecare.in/:splat"
  status = 301
  force = true
